---
# https://pre-commit.com/#installation
default_stages: [commit, push]
default_language_version:
  # force all unspecified Python hooks to run python3
  python: python3
minimum_pre_commit_version: '2.18.1'
repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        name: Run codespell
        description: Check spelling with codespell
        entry: codespell --ignore-words=codespell.txt
        exclude: ^docs/image|^spark/common/src/test/resources
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      # - id: check-docstring-first
      # - id: check-executables-have-shebangs
      # - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      # - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: \.svg$|^docs/image|^spark/common/src/test/resources
      - id: trailing-whitespace
        files: \.(ipynb|java|py|R|scala|sh|xml|yaml|yml)$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        name: Run markdownlint
        description: Check Markdown files with markdownlint
        entry: markdownlint -c .github/linters/.markdown-lint.yml .
        exclude: ^\.github/.*$
        types: [markdown]
        files: \.(md|mdown|markdown)$
