[tool.bandit]
skips = ["B101", "B403", "B405", "B608"]

[tool.isort]
profile = "black"

[tool.vulture]
min_confidence = 100
paths = ["docs/usecases/utilities.py", "python/", "spark-version-converter.py"]
sort_by_size = true
