version: "3.9"
volumes:
  shared-workspace:
    name: "shared-workspace"
    driver: local
services:
  spark-master:
    image: spark-master
    build: 
      context: .
      dockerfile: spark-master.dockerfile
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
      - ./examples:/opt/workspace/examples:rw
  spark-worker-1:
    image: spark-worker
    build: 
      context: .
      dockerfile: spark-worker.dockerfile
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=4g
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
      - ./examples:/opt/workspace/examples:rw
    depends_on:
      - spark-master
  spark-worker-2:
    image: spark-worker
    build: 
      context: .
      dockerfile: spark-worker.dockerfile
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=4g
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
      - ./examples:/opt/workspace/examples:rw
    depends_on:
      - spark-master
  jupyterlab:
    image: kartikeyhadiya/sedona_jupyterlab:1.4.0
    build: 
      context: .
      dockerfile: jupyterlab.dockerfile
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace
      - ./examples:/opt/workspace/examples:rw
    depends_on:
      - spark-master