name: Docker build

on:
  push:
    branches:
      - master
    paths:
      - 'docker/**'
  pull_request:
    branches:
      - '*'

env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=60
      
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        include:
          - spark: 3.4.1
            sedona: 1.4.1
          - spark: 3.4.1
            sedona: latest
          - spark: 3.3.2
            sedona: latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - env:
        SPARK_VERSION: ${{ matrix.spark }}
        SEDONA_VERSION: ${{ matrix.sedona }}
      run: ./docker/spark-sedona-jupyterlab/build.sh $SPARK_VERSION $SEDONA_VERSION
