name: Docs build
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'docs-overrides/**'
      - 'mkdocs.yml'
      - 'R/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'docs/**'
      - 'docs-overrides/**'
      - 'mkdocs.yml'
      - 'R/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: pip install mkdocs-material
    - run: pip install mkdocs-macros-plugin
    - run: pip install mkdocs-git-revision-date-localized-plugin
    - run: pip install mike
    - run: sudo apt update
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: release
        use-public-rspm: true
    - name: Query R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache: true
        extra-packages: |
          any::pkgdown
        working-directory : './R'
    - run: Rscript -e 'pkgdown::build_site(pkg = "./R", preview = FALSE, override = list(destination = "../docs/api/rdocs"))'
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - run: git config --global user.name = "test-name"
    - run: git config --global user.email = "test-email@abc.com"
    - run: mike deploy --update-aliases current-snapshot
    - run: mkdir staging
    - run: cp -r site/* staging/
    - uses: actions/upload-artifact@v4
      with:
        name: generated-docs
        path: staging
