name: Example project build
on:
  push:
    branches:
      - master
    paths:
      - 'examples/**'
      - '.github/workflows/example.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - 'examples/**'
      - '.github/workflows/example.yml'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - spark: '3.5.0'
            spark-compat: '3.5'
            sedona: '1.5.3'
            geotools: '28.2'
            java: '11'
          - spark: '3.5.0'
            spark-compat: '3.5'
            sedona: '1.5.3'
            geotools: '28.2'
            java: '8'
          - spark: '3.4.2'
            spark-compat: '3.4'
            sedona: '1.5.3'
            geotools: '28.2'
            java: '8'
          - spark: '3.3.4'
            spark-compat: '3.0'
            sedona: '1.5.3'
            geotools: '28.2'
            java: '8'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - env:
        SPARK_VERSION: ${{ matrix.spark }}
        SPARK_COMPAT_VERSION: ${{ matrix.spark-compat }}
        SEDONA_VERSION: ${{ matrix.sedona }}
        GEOTOOLS_VERSION: ${{ matrix.geotools }}
      run: |
        echo "Running Maven command: mvn clean install -Dspark.version=${SPARK_VERSION} -Dgeotools.version=${GEOTOOLS_VERSION} -Dspark.compat.version=${SPARK_COMPAT_VERSION} -Dsedona.version=${SEDONA_VERSION}"
        (cd examples/spark-sql; mvn clean install -Dspark.version=${SPARK_VERSION} -Dgeotools.version=${GEOTOOLS_VERSION} -Dspark.compat.version=${SPARK_COMPAT_VERSION} -Dsedona.version=${SEDONA_VERSION}; java -jar target/sedona-spark-example-1.0.0.jar)
    - env:
        SPARK_VERSION: ${{ matrix.spark }}
        SPARK_COMPAT_VERSION: ${{ matrix.spark-compat }}
        SEDONA_VERSION: ${{ matrix.sedona }}
        GEOTOOLS_VERSION: ${{ matrix.geotools }}
      run: |
        echo "Running Maven command: mvn clean install -Dgeotools.version=${GEOTOOLS_VERSION}"
        (cd examples/flink-sql;mvn clean install;java -jar target/sedona-flink-example-1.0.0.jar)
