name: Scala and Java build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
      
jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - spark: 3.3.0
            scala: 2.13.8
            jackson: 2.13.3
          - spark: 3.2.0
            scala: 2.13.5
            jackson: 2.12.3
          - spark: 3.3.0
            scala: 2.12.15
            jackson: 2.13.3
          - spark: 3.2.0
            scala: 2.12.15
            jackson: 2.12.3
          - spark: 3.1.2
            scala: 2.12.15
            jackson: 2.10.0
          - spark: 3.0.3
            scala: 2.12.15
            jackson: 2.10.0
          - spark: 2.4.8
            scala: 2.12.15
            jackson: 2.6.7
          - spark: 2.4.8
            scala: 2.11.8
            jackson: 2.6.7

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - run: git submodule update --init --recursive # Checkout Git submodule if necessary
    - env:
        SPARK_VERSION: ${{ matrix.spark }}
        SCALA_VERSION: ${{ matrix.scala }}
        JACKSON_VERSION: ${{ matrix.jackson }}
      run: |
        if [ ${SPARK_VERSION:0:1} == "3" ]; \
        then mvn -q clean install -Dscala=${SCALA_VERSION:0:4} -Dspark=3.0 -Dspark.version=${SPARK_VERSION} -Dsedona.jackson.version=${JACKSON_VERSION}; \
        else mvn -q clean install -Dscala=${SCALA_VERSION:0:4} -Dspark=2.4 -Dspark.version=${SPARK_VERSION} -Dsedona.jackson.version=${JACKSON_VERSION}; fi \
    - run: mkdir staging
    - run: cp core/target/sedona-*.jar staging
    - run: cp sql/target/sedona-*.jar staging
    - run: cp viz/target/sedona-*.jar staging
    - run: cp python-adapter/target/sedona-*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: generated-jars
        path: staging
