name: Python build wheels

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
      
jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.12.0
      env:
        CIBW_SKIP: 'pp* *musl*'
        CIBW_ARCHS: 'auto64'
      with:
        package-dir: python
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
